"""What the shell needs from doit, emitted by doit.

Two blocks lived in dotfiles and referred to doit's internals: an eleven-line
startup gate that tested `-x ~/.local/bin/menu-review`, and a completion function
that read a cache path by hand. Both broke the moment the binaries collapsed into
one, which is the tell — a config repo was carrying doit's implementation details
because there was nowhere else to put them.

Now dotfiles carries one `eval` line per block and doit carries the block. When
the state path or the verb list changes, it changes here, and every machine picks
it up on the next shell rather than on the next dotfiles edit.

The completion reads a flat file rather than calling doit. Completion has to feel
instant and starting a Python process does not, so every run of the draw leaves
`next-names.txt` behind for the shell to read with no subprocess at all. That is
also why this is a generated script rather than typer's `--install-completion`:
typer's completion spawns the program on every TAB.

Three blocks, not one, because they load at different points and answer to
different switches: the nudge prints and is gated on wanting reminders, the
completion is silent and unconditional, and the widgets are silent, unconditional
and bound to a key. Folding any of them into another would put a keybinding or a
completion behind a toggle that has nothing to do with either.
"""

from typing import Annotated

import typer

from doit.paths import xdg_cache_home
from doit.paths import xdg_state_home

SHELLS = ('zsh',)

# Default gate, in minutes, when no interval has been set. Four hours means at
# most twice a working day, which is the point of a nudge rather than a banner.
DEFAULT_NUDGE_MINUTES = 240


def zsh_init() -> str:
    """The startup nudge gate.

    The gate is a marker-mtime check, so doit starts at most once per interval
    rather than on every shell. The nudge is silent when nothing is due, so a
    clear day adds no startup cost beyond this test.

    Marker and interval live in the state dir together, so the schedule is a
    rolling one shared across machines rather than once per machine.
    """
    state = xdg_state_home() / 'doit'
    return f"""\
# doit — surface the review register's due items on the first shell of each
# interval. Generated by `doit shell-init zsh`; edit it there, not here.
if (( $+commands[doit] )); then
  _doit_state="{state}"
  _doit_marker="$_doit_state/nudge"
  _doit_mins="$(cat "$_doit_state/nudge-interval-minutes" 2>/dev/null || echo {DEFAULT_NUDGE_MINUTES})"
  if [[ ! -f "$_doit_marker" || -n "$(find "$_doit_marker" -mmin +"$_doit_mins" 2>/dev/null)" ]]; then
    mkdir -p "$_doit_state"
    : > "$_doit_marker"  # touch: mtime = now = last-nudged
    doit review nudge
  fi
  unset _doit_state _doit_marker _doit_mins
fi
"""


def zsh_completion() -> str:
    """Completion for the verbs, and for pursuit names from the cache."""
    cache = xdg_cache_home() / 'doit' / 'next-names.txt'
    return f"""\
#compdef doit
# Generated by `doit completion zsh`; edit it there, not here.

_doit_pursuits() {{
  local cache="{cache}"
  [[ -r $cache ]] || return 1
  local -a pursuits
  # name<TAB>description in the file, name:description for _describe.
  pursuits=("${{(@f)$(<$cache)}}")
  pursuits=("${{(@)pursuits//$'\\t'/:}}")
  _describe -t pursuits 'pursuit' pursuits
}}

_doit() {{
  local -a verbs
  verbs=(
    'next:What to do now, drawn from your weighted pursuits'
    'log:Record having done one'
    'skip:Pass on one — suppressed, weight untouched'
    'dashboard:Everything outstanding across your apps, in lanes'
    'find:Search across everything you own'
    'choose:Pick one thing and print what you would type'
    'launch:Your areas and every tool you own'
    'show:Everything known about one subject'
    'pursuits:The weights the draw runs on'
    'review:What is due to revisit'
    'labs:Hands-on practice that is due now'
    'workflows:The reference cards'
    'content:The cards and Labs checkout'
    'sources:Which apps doit asks for lanes'
    'kit:Everything you own, and what you actually reach for'
  )

  if (( CURRENT == 2 )); then
    _describe -t verbs 'doit command' verbs
    return
  fi

  # `log` and `skip` both take a pursuit, and they are the two you type most.
  case "$words[2]" in
    log|skip) (( CURRENT == 3 )) && _doit_pursuits ;;
  esac
}}

compdef _doit doit
"""


def zsh_widgets() -> str:
    """The line-editor half of `doit choose`.

    doit is a subprocess and the line editor belongs to its parent, so the insert
    is something doit can only ever emit. What it emits names one public verb and
    nothing else — no state path, no cache path, no index internals — which is
    the property that keeps this block from breaking the way the two it replaced
    did.

    A separate block from the startup nudge because the nudge is gated on wanting
    reminders, and a keybinding that disappears when an unrelated toggle is
    turned off is a keybinding nobody trusts.
    """
    return """\
# doit — pick anything you own and land it on the command line, ready to run or
# edit. Generated by `doit shell-widgets zsh`; edit it there, not here.

# Replaces the line you are on.
doit-choose-widget() {
  local chosen
  chosen="$(doit choose)"
  if [[ -n "$chosen" ]]; then
    BUFFER="$chosen"
    CURSOR=${#BUFFER}
  fi
  # fzf paints over the prompt and does not put it back.
  zle reset-prompt
}
zle -N doit-choose-widget

# Loads the next prompt instead, for when the line you are on is worth keeping.
dochoose() {
  local chosen
  chosen="$(doit choose)"
  [[ -n "$chosen" ]] && print -z -- "$chosen"
}
"""


GENERATORS = {
    'zsh': {'init': zsh_init, 'completion': zsh_completion, 'widgets': zsh_widgets},
}


def emit(shell: str, kind: str) -> int:
    if shell not in GENERATORS:
        raise typer.BadParameter(f'no {kind} for {shell}; doit generates: {", ".join(SHELLS)}')
    # Plain print: this is a script another process evals, not a message.
    print(GENERATORS[shell][kind]())
    return 0


def shell_init_command(
    shell: Annotated[str, typer.Argument(help=f'Which shell: {", ".join(SHELLS)}.')],
) -> None:
    """Print the shell startup block. Add `eval "$(doit shell-init zsh)"` to your rc."""
    raise typer.Exit(emit(shell, 'init'))


def shell_widgets_command(
    shell: Annotated[str, typer.Argument(help=f'Which shell: {", ".join(SHELLS)}.')],
) -> None:
    """Print the line-editor block for `doit choose`, and bind it to a key.

    zsh only, because `print -z` and the ZLE buffer are. Everywhere else the same
    pick is `$(doit choose)`, which prints the invocation and inserts nothing.
    """
    raise typer.Exit(emit(shell, 'widgets'))


def completion_command(
    shell: Annotated[str, typer.Argument(help=f'Which shell: {", ".join(SHELLS)}.')],
) -> None:
    """Print the completion script. Source it from your fpath or rc."""
    raise typer.Exit(emit(shell, 'completion'))
